spiders_buffer_size: 3
infinite_scrolling:
  headless: true
  delay_milis: 500
  scroll_delay_milis: 250
  scroll_checks: 20
metro:
  name: "metro"
  base_url: "https://www.metro.pe"
  selector: ".product-item"
wong:
  name: "wong"
  base_url: "https://www.wong.pe"
  selector: ".product-item"
plaza_vea:
  name: "plaza_vea"
  base_url: "https://www.plazavea.com.pe"
  selector: ".Showcase"
  delay_milis: 500
  next_page_selector: "notsetted"
