out_path: "output_dev"
infinite_scrolling:
  scroll_checks: 2
metro:
  subroutes:
    - "frutas-y-verduras"
    - "desayuno"
wong:
  subroutes:
    - "frutas-y-verduras"
    - "desayuno"
plaza_vea:
  subroutes:
    - "frutas-y-verduras"
    - "carnes-aves-y-pescados"
