out_path: "output"
metro:
  subroutes:
    - "frutas-y-verduras"
    - "carnes-aves-y-pescados"
    - "desayuno"
    - "lacteos"
    - "embutidos-y-fiambres"
    - "abarrotes"
    - "panaderia-y-pasteleria"
    - "comidas-y-rostizados"
    - "congelados"
    - "aguas-y-bebidas"
    - "cervezas-vinos-y-licores"
    - "limpieza"
    - "higiene-salud-y-belleza"
    - "ninos-y-bebes"
wong:
  subroutes:
    - "frutas-y-verduras"
    - "carnes-aves-y-pescados"
    - "desayuno"
    - "lacteos"
    - "embutidos-y-fiambres"
    - "abarrotes"
    - "panaderia-y-pasteleria"
    - "comidas-y-rostizados"
    - "congelados"
    - "aguas-y-bebidas"
    - "cervezas-vinos-y-licores"
    - "limpieza"
    - "higiene-salud-y-belleza"
    - "ninos-y-bebes"
plaza_vea:
  subroutes:
    - "frutas-y-verduras"
    - "carnes-aves-y-pescados"
    - "desayunos"
    - "lacteos-y-huevos"
    - "quesos-y-fiambres"
    - "abarrotes"
    - "panaderia-y-pasteleria"
    - "pollo-rostizado-y-comidas-preparadas"
    - "congelados"
    - "bebidas"
    - "limpieza"
    - "cuidado-personal-y-salud"
    - "bebe-e-infantil"
    - "mercado-saludable"
