name: Launch script
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1,4' # Mondays and Thursdays

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
      - name: Run scrapper and push
        run: |
          export DISPLAY=:99
          chromedriver --port=4444 --disable-dev-shm-usage &
          tar -xzf peru-prices.tar.gz
          APP_ENVIRONMENT=production ./peru-prices
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: extractions/setup-just@v1
      - name: Render quarto site
        run: |
          just render-exec-site
          timestamp=$(date -u)
          git commit -m "Latest quarto site: ${timestamp}" || exit 0
          git push
